//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductRatings = new HashSet<ProductRating>();
        }
    
        public int id { get; set; }
        public string product_name { get; set; }
        public string image_name { get; set; }
        public string detail { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> discounted_price { get; set; }
        public Nullable<bool> campaign_status { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public string status { get; set; }
        public Nullable<int> category_id { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductRating> ProductRatings { get; set; }
    }
}
